export const SITE_LINKS = {
  home: '/',
  institution: '/institution',
  explore: '/explore',
  pricing: '/pricing',
  download: '/download',
  signup: '/signup',
  login: '/login',
  contact: '#contact',
  documentation: '/documentation',
  ecosystem: '#ecosystem',
  ctcScore: '#ctc-score',
  contests: '#contests',
  infrastructure: '#infrastructure',
  faq: '#faq',
  privacy: '/privacy',
  terms: '/terms',
  email: 'mailto:info@crackthecampus.com',
  addressMap: 'https://maps.app.goo.gl/y6P9HgeWedwsfCiz9',
  instagram: 'https://www.instagram.com/crackthecampus_',
  linkedin: 'https://www.linkedin.com/company/crackthecampus',
};
